---
name: "Shopping application image build & deployement (Dev)"
on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      packer_version: "1.9.4"
    steps:
      - name: "Checkout From Repository"
        uses: actions/checkout@v3
      - name: "Installing Packer"
        uses: hashicorp/setup-packer@main
        with:
          version: ${{env.packer_version}}
      - name: "Packer Initialization"
        run: packer init .
        working-directory: ./packer/
      - name: "Packer Validate"
        run: packer validate -var-file="dev.pkvars.hcl" .
        working-directory: ./packer/
      - name: "Format packer template"
        run: packer fmt .
        working-directory: ./packer/
      - name: "Packer Build Image"
        run: packer build -var-file="dev.pkvars.hcl"
        working-directory: ./packer/
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.DEV_ACCESS_KEY}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.DEV_SECRET_KEY}}
          AWS_DEFAULT_REGION: ${{secrets.DEV_REGION}}
